### ISSUE TITLE
Specify what is the icon position on Button

### ISSUE THREAD

**Issue by mindsers** [ferpection/uikit#39]
`Button` displays the icon on left of the button but we might want to display it on the right. Add an attribute on `Button` to specify where we want to display the icon.

**Comment by mindsers** [comment]
Done

**Comment by AminDannak** [comment]
> Done

what do mean Done? How did you manage to do that?

**Comment by mindsers** [comment]
I added the attribute to `Button` component as asked in the issue. See #50
